# Generated by Django 6.0 on 2026-01-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Newapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
