# Generated by Django 6.0 on 2026-01-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Newapp", "0002_product_delete_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Person",
        ),
    ]
