# Generated by Django 6.0 on 2026-01-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Newapp", "0003_rename_product_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="pH",
            field=models.IntegerField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
