# Generated by Django 6.0 on 2026-01-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Newapp", "0004_person_ph"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="pH",
            field=models.IntegerField(null=True),
        ),
    ]
